version: '3.5'
services:
  web:
    container_name: srv-zabbix
    image: jorarmarfin/zabbix:4.2
    volumes:
      - ./zabbix/backup:/backup
    ports:
      - 9007:80
      - 10051:10051
    networks: 
      - net-zabbix
  db:
    container_name: srv-zabbix-mysql
    image: jorarmarfin/mysql:5.7-zabbix42
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/backup:/backup
    networks:
      - net-zabbix
  ubuntu:
    container_name: srv-ubuntu
    image: jorarmarfin/ubuntu:latest
    networks: 
      - net-zabbix
networks: 
  net-zabbix:
