version: '3.5'
services:
  server:
    container_name: 'srv-zabbix-server'
    image: zabbix/zabbix-server-mysql:latest
    restart: always
    environment:
      - DB_SERVER_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./data_zabbix_server_alertscripts:/usr/lib/zabbix/alertscripts
      - ./data_zabbix_server_externalscripts:/usr/lib/zabbix/externalscripts
      - ./data_zabbix_server_modules:/usr/lib/zabbix/modules
      - ./data_zabbix_server_enc:/usr/lib/zabbix/enc
      - ./data_zabbix_server_ssl_cert:/usr/lib/zabbix/ssl/certs
      - ./data_zabbix_server_ssl_keys:/usr/lib/zabbix/ssl/keys
      - ./data_zabbix_server_ssl_ca:/usr/lib/zabbix/ssl/ssl_ca
      - ./data_zabbix_server_snmptraps:/usr/lib/zabbix/snmptraps
      - ./data_zabbix_server_mibs:/usr/lib/zabbix/mibs
    ports:
      - ${PORT_SERVER}:10051
  frontend:
    container_name: 'srv-zabbix-web'
    image: zabbix/zabbix-web-apache-mysql:latest
    restart: always
    environment:
      - DB_SERVER_HOST=${DB_HOST}
      - ZBX_SERVER_HOST=${SERVER_HOST}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - PHP_TZ="America/Recife"
    volumes:
      - ./data_zabbix_web:/etc/ssl/apache2
    ports:
      - ${PORT_WEB}:80